# YOLOv10s-calorie specific config
model: yolov10s-calorie.yaml
data: food_calorie.yaml
epochs: 100
batch: 64
imgsz: 640

optimizer: auto
lr0: 0.01
momentum: 0.937
weight_decay: 0.0005

loss: 
  detection_weight: 1.0
  calorie_weight: 0.5
  cls_weight: 0.3

# Data augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
translate: 0.1
scale: 0.5
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
